---
layout: cv
title: Elroe Woldemichael CV
---

<div id="webaddress">
<a href="https://www.linkedin.com/in/elroe-woldemichael/">Linkedin</a>
</div>


## Education
Bachelor of Science in Computer Science | Brigham Young University - Idaho | 
Rexburg, ID

 - Emphasis in Software Design and Functional Programming
 - GPA: 3.98 (Summa Cum Laude)
 - Scholarship: Brigham Young University-Idaho Academic Grant (2021-2024)
 - Society: President of Computing Society
 - Relevant Courses: Calculus, OOP (C#), Data Structures & Algorithm, and Modularization Design 


### Work Experience
Student Engineer @ Family Search - Sep 2024 - Present

SDET Intern @ Family Search  - Apr 2024 - Sep 2024

Online CS Tutor @ BYU-I - Apr 2022 - Apr 2024

### Experiential Learning Projects

 Learning Project | Market Real Estate | Salt Lake City, UT



 - Designed and developed a full stack real estate web application using Amplify, Figma, and other AWS services, 
offering users a platform marketplace to effortlessly list properties for sale or rent
 - Implemented advanced search features allowing prospective buyers or renters to refine property searches based 
on location, type, price, and amenities, ensuring a tailored and efficient browsing experience daily
 
 
 Learning Project | English Ease | Rexburg, ID
 October 2023 - December 2023


 - Led and Collaborated with a team of 5 to build an English learning web app leveraging React and React Native 
libraries
 - Constructed and implemented 5+ features to enhance fun English learning, including sections on animals, 
alphabets, food, games and body parts
 
 
 Learning Project | Goal Tracker | Salt Lake City, UT
 February 2023


 - Designed and developed a goal-tracking program to incentivize users to achieve personal goals through 
gamification techniques and includes 7+ features such as point systems and personalized celebrations
 - Built a program using object-oriented programming concepts such as encapsulation, inheritance, and 
polymorphism to accomplish a 90% high code reuse and design flexibilit


## Volunteer Experience

`2012`
Full-time volunteer | The Church of Jesus Christ of Latter-Day | Salt Lake City, 
UT


 June 2019 - June 2021
 - Performed 70-80 hours on a weekly basis speaking both English and Amharic (Ethiopia) fluently
 - Prepared goals and plans for 100+ people to learn important ways to achieve personal goals
 - Adjusted to different circumstances during pandemic and applied phone and virtual lessons on a daily basis



## Technical Skills
 - Programming Languages : C++ | Python | C# | MySQL | Erlang | Javascript | HTML | CSS
 - Tools : Git | GitHub | visual studio | vs code
 - Soft skills : Teamwork | Problem solving | Adaptability | Critical thinking

